# Generated by Django 4.2.11 on 2026-02-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Tên khách')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='SĐT khách')),
                ('address', models.TextField(verbose_name='Địa chỉ giao')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('total_price', models.IntegerField(verbose_name='Tổng tiền')),
                ('status', models.CharField(default='Chờ xử lý', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Cửa hàng')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.order')),
            ],
        ),
    ]
