# Generated by Django 4.2.11 on 2026-03-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_category_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_qrs/', verbose_name='Ảnh QR Thanh Toán'),
        ),
    ]
