# Generated by Django 4.2.11 on 2026-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Mã đơn 6 số'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Giá nhập lúc mua'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Giá nhập (VNĐ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Giá bán (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='qr_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh QR Thanh Toán'),
        ),
    ]
