# Generated by Django 4.2.11 on 2026-05-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_order_order_code_orderitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm'),
        ),
    ]
