# Generated by Django 4.2.11 on 2026-05-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('total_spent', models.IntegerField(default=0, verbose_name='Tổng chi tiêu')),
                ('order_count', models.IntegerField(default=0, verbose_name='Số đơn đã đặt')),
                ('last_order_at', models.DateTimeField(auto_now=True, verbose_name='Lần cuối đặt hàng')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Cửa hàng')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.customer', verbose_name='Khách hàng hệ thống'),
        ),
    ]
