# Generated by Django 4.2.11 on 2026-05-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Đơn hàng gần nhất'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='Tổng số đơn'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.store', verbose_name='Thuộc cửa hàng'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'phone')},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_order_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order_count',
        ),
    ]
