# Generated by Django 4.2.11 on 2026-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_order_customer_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default='22:00', verbose_name='Giờ đóng cửa'),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Lời giới thiệu/Tagline'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái mở cửa'),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(default=10.762622, verbose_name='Vĩ độ (Lat)'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(default=106.660172, verbose_name='Kinh độ (Lng)'),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default='07:00', verbose_name='Giờ mở cửa'),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_payment_url',
            field=models.FileField(blank=True, null=True, upload_to='store_qrs/', verbose_name='Mã QR thanh toán'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Địa chỉ'),
            preserve_default=False,
        ),
    ]
