# Generated by Django 4.2.11 on 2026-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú món'),
        ),
    ]
